### PR TITLE
Allow parametric images from tables with BG measurements

### LINKED ISSUE #65: Parametric images do not account tables with background measurements
Hi Robert @haesleinhuepf ,

The parametric images from table does not support tables where you have a label `0` meaning measurements from the background.
It wrongly assigns values to labels shifted by one. The problem is [here](https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/59ff289fa08c621acfff8e87e32cf0f6ea10c7d0/napari_skimage_regionprops/_parametric_images.py#L88). It always insert a 0, no matter the situation.

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by zoccoler**
Insert 0 to measurements only if background measurements are absent in tables.

This should fix #65

### CODE REVIEW

**Comment by zoccoler** [comment]
One of the tests if failing now, I am checking it.

**Comment by haesleinhuepf** [comment]
Hi  Marcelo,

if we're sure that it works again, I'm happy to merge it. Afterwards, we should work on the next step, replacing our mapping-method as discussed in #48 . I would love to hear your opinion about how to do it exactly. My only concern is backwards-compatibility. Quite some other plugins use the functions we have here. Thus, we cannot modify  behaviour. We can only extend it and deprecate old stuff.

Thanks!

Best,
Robert

**Comment by zoccoler** [comment]
Hi Robert @haesleinhuepf ,

Totally agree. This should work now. I am still using `numpy.take` and not putting `0` if there is already a label `0` in the table with some value.

About replacing it by `map_array`, I will give it a quick try and do some benchmarking, but it looks pretty similar to me. 
Is the only benefit of that having the possibility of non-sequential labels?
Also, should we keep `cle.replace_intensities`?

**Comment by zoccoler** [comment]
I found the problem. In the timelapse tests, the label images have label values up to 4, but `numpy.take` works with indices. So, since we have 4 measurements from these 4 labels (max index is 3), this throws an error. It surprises me that this error did not show up before.

**Comment by zoccoler** [comment]
This won't merge, please refer for #67 for an extension of this.

**Pull request closed without merging**
